UiKit
softwarrior/WebCourse pull request #2
Opened 2022-08-22 12:11 UTC by softwarrior

UiKit

2022-08-24 01:07 UTC, Muslik requested changes
- В dropdown слева checkbox. По клику на текст checkbox должен выбираться. ПО Клику на ВЕСЬ РЯД. Не должно быть отступов слева и справа.
- В dropdown справа radio. По клику на текст строка должна выбираться.
- Кнопка только с иконкой -> Не по макету
- Кнопка не может быть ограничена по ширине.

2022-08-24 01:07 UTC, Muslik commented on uikit/Uikit.html
> +                <div class="input">
Неа. .input должен быть у блока c <input />. В конце концов вы его должны переиспользовать

2022-08-24 01:07 UTC, Muslik commented on uikit/Uikit.html
> +                    <div class="searchbar">
Тоже что и с input-ом. .searchbar должен быть блок только с searchbar инпутом.

2022-08-24 01:07 UTC, Muslik commented on uikit/Uikit.html
> +                        <form class="searchbar__form">
Обертка из form не нужна абсолютно тут. Это же ui-kit. Форма будет уже в полноценном проекте

2022-08-24 01:07 UTC, Muslik commented on uikit/Uikit.html
> +                <form class="buttons__table">
Форма не нужна

2022-08-24 01:07 UTC, Muslik commented on uikit/Uikit.html
> +                            <button class="button button_primary-size_large">
Разделяем модификаторы на тему и размер

2022-08-24 01:07 UTC, Muslik commented on uikit/Uikit.html
> +                            <button class="button button_primary-size_large button_length_long button_disabled" disabled>
Зачем length long если есть size_large

2022-08-24 01:07 UTC, Muslik commented on uikit/Uikit.html
> +                            <form class="dropdown__form">
Форма не нужна

2022-08-24 01:07 UTC, Muslik commented on uikit/Uikit.html
> +                                    <button class="dropdown__button dropdown__button_transparent">
Переиспользуем кнопки которые делали раньше

2022-08-27 15:20 UTC, softwarrior commented on uikit/Uikit.html
> +                <div class="input">
Большое спасибо за ревью! Замечания исправил в коммите.

2022-08-27 15:20 UTC, softwarrior commented on uikit/Uikit.html
> +                    <div class="searchbar">
Большое спасибо за ревью! Замечания исправил в коммите.

2022-08-27 15:20 UTC, softwarrior commented on uikit/Uikit.html
> +                        <form class="searchbar__form">
Большое спасибо за ревью! Замечания исправил в коммите.

2022-08-27 15:21 UTC, softwarrior commented on uikit/Uikit.html
> +                <form class="buttons__table">
Большое спасибо за ревью! Замечания исправил в коммите.

2022-08-27 15:21 UTC, softwarrior commented on uikit/Uikit.html
> +                            <button class="button button_primary-size_large">
Большое спасибо за ревью! Замечания исправил в коммите.

2022-08-27 15:21 UTC, softwarrior commented on uikit/Uikit.html
> +                            <button class="button button_primary-size_large button_length_long button_disabled" disabled>
Большое спасибо за ревью! Замечания исправил в коммите.

2022-08-27 15:21 UTC, softwarrior commented on uikit/Uikit.html
> +                            <form class="dropdown__form">
Большое спасибо за ревью! Замечания исправил в коммите.

2022-08-27 15:21 UTC, softwarrior commented on uikit/Uikit.html
> +                                    <button class="dropdown__button dropdown__button_transparent">
Большое спасибо за ревью! Замечания исправил в коммите.

2022-08-27 22:52 UTC, Muslik approved these changes
Есть пара замечаний. Прикреплю видео.

2022-08-29 10:38 UTC, merged